# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:bookworm"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bookworm"
  i386: "ghcr.io/home-assistant/i386-base-base-debian:bookworm"
labels:
  org.opencontainers.image.title: "Unpolller for Home Assistnat"
  org.opencontainers.image.description: "Unpoller"
  org.opencontainers.image.source: "https://github.com/cookytime/addon-unpoller"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
