# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Unpoller add-on
version: "1.0"
slug: unpoller
description: Unpoller add-on
url: "https://github.com/cookytime/addons-unpoller/tree/main/unpoller"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/cookytime/{arch}-addon-example"
