# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Unpoller add-on
version: "1.2"
slug: unpoller
description: Unpoller add-on
url: "https://github.com/cookytime/addons-unpoller/tree/main/unpoller"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
  - addon_config:rw
options:
  influxdb_url: http://47c55538-influxdbv2:9200
  influxdb_token: EnterToken
  influxdb_org: GlenCookTech
  influxdb_bucket: unifi 
  unifi_user: ha
  unifi_pass: naLc8mKV62oy49PVDtm6
  unifi_url: https://192.168.1.1
  unifi_save_dpi: True
schema:
  influxdb_url: str
  influxdb_token: str
  influxdb_org: str
  influxdb_bucket: str
  unifi_user: str
  unifi_pass: str
  unifi_url: str
  unifi_save_dpi: bool
image: "ghcr.io/cookytime/{arch}-addon-unpoller"
